/**
 * POST /api/ai/generate-smeta
 *
 * Takes a text description of a construction project and returns
 * a structured Smeta (cost estimate) generated by Claude.
 *
 * This is the REAL AI pipeline — not a mock. Every line item is
 * generated by Claude Sonnet 4.6 using the construction-expert system
 * prompt, with rates grounded in CIS/Central Asian market prices.
 */

import Anthropic from "@anthropic-ai/sdk";
import { NextResponse } from "next/server";

const SYSTEM_PROMPT = `Ты — опытный инженер-сметчик с 20-летним стажем работы на строительных проектах в Центральной Азии (Кыргызстан, Казахстан, Узбекистан) и России. Твоя задача — по описанию объекта от пользователя составить детальную локальную смету.

ПРИНЦИПЫ:
1. Всегда указывай единицу измерения, количество, цену за единицу, итог по строке.
2. Для каждой строки указывай источник цены: "history" (если это типичная рыночная цена для региона), "market" (если цена актуальная рыночная), или "needs_clarification" (если данных недостаточно для точной оценки).
3. Если информации недостаточно — не выдумывай. Используй "needs_clarification" и разумные допущения, которые перечисли в assumptions.
4. Работай в KGS (сомах КР), RUB (рублях РФ) или USD в зависимости от региона. По умолчанию — KGS для Кыргызстана, RUB для России.
5. Структурируй смету по разделам: земляные работы, фундамент, несущие конструкции, кровля, отделка, инженерные сети, благоустройство. Включай только те разделы, которые релевантны описанию.
6. Каждый total = qty * rate. Общий total = сумма всех total по строкам.
7. Цены должны быть реалистичными для 2025-2026 года для указанного региона.

ФОРМАТ ОТВЕТА — строго JSON, ничего кроме JSON:
{
  "region": "Бишкек",
  "currency": "KGS",
  "sections": [
    {
      "name": { "ru": "Земляные работы", "en": "Earthworks" },
      "items": [
        {
          "id": "li_1",
          "description": { "ru": "Разработка грунта экскаватором", "en": "Excavator earthworks" },
          "unit": "м³",
          "qty": 120,
          "rate": 450,
          "total": 54000,
          "source": "market"
        }
      ]
    }
  ],
  "total": 54000,
  "assumptions": ["Глубина промерзания 1.2 м", "..."],
  "clarifying_questions": ["Тип грунта на участке?"]
}`;

export async function POST(request: Request) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: { code: "config", message: "ANTHROPIC_API_KEY not set. Add it in Vercel environment variables." } },
      { status: 500 },
    );
  }

  let body: { text: string; projectId?: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: { code: "validation", message: "Invalid JSON body" } },
      { status: 400 },
    );
  }

  if (!body.text || body.text.trim().length < 10) {
    return NextResponse.json(
      { error: { code: "validation", message: "Provide a project description (at least 10 characters)" } },
      { status: 400 },
    );
  }

  try {
    const client = new Anthropic({ apiKey });

    const msg = await client.messages.create({
      model: "claude-sonnet-4-6-20250514",
      max_tokens: 4096,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: body.text }],
    });

    const raw = (msg.content[0] as { type: string; text: string }).text.trim();

    // Strip ```json fences if present
    let json = raw;
    if (json.startsWith("```")) {
      json = json.split("```")[1];
      if (json.startsWith("json")) json = json.slice(4);
      json = json.trim();
    }

    const smeta = JSON.parse(json);

    // Add metadata
    smeta.id = "smeta_" + Date.now().toString(36);
    smeta.project_id = body.projectId ?? "proj_adhoc";
    smeta.status = "draft";
    smeta.created_at = new Date().toISOString();

    return NextResponse.json({ smeta });
  } catch (err) {
    const message = err instanceof Error ? err.message : "AI generation failed";
    return NextResponse.json(
      { error: { code: "ai_error", message } },
      { status: 500 },
    );
  }
}
