/**
 * POST /api/ai/generate-deck
 *
 * Takes a text description of a project and returns structured DeckData
 * JSON for a bilingual investor presentation, generated by Claude.
 *
 * This is the REAL AI pipeline — Claude structures the content,
 * translates RU↔EN, and fills every field of the DeckData schema.
 */

import Anthropic from "@anthropic-ai/sdk";
import { NextResponse } from "next/server";

const SYSTEM_PROMPT = `Ты — старший консультант McKinsey, специализирующийся на инвестиционных проектах в строительстве и инфраструктуре Центральной Азии. Твоя задача — по описанию проекта от пользователя подготовить структурированные данные для инвестиционной презентации.

КРИТИЧЕСКИЕ ПРАВИЛА:
1. НИКОГДА не выдумывай цифры. Если в описании нет конкретной суммы — пиши "требует уточнения / TBD".
2. Сохраняй формулировки из исходника. Не округляй и не изобретай детали.
3. Переводи на английский САМ — используй профессиональный инвестиционный английский.
4. Каждое текстовое поле должно быть двуязычным: {"ru": "...", "en": "..."}.
5. Названия организаций, географические названия — оставляй как в оригинале.

ФОРМАТ — строго JSON, соответствующий структуре:
{
  "project_slug": "project-name",
  "language_primary": "ru",
  "language_secondary": "en",
  "cover": {
    "title": {"ru": "...", "en": "..."},
    "subtitle": {"ru": "...", "en": "..."},
    "info_cards": [
      {"icon": "star", "label": {"ru": "Проект", "en": "Project"}, "value": {"ru": "...", "en": "..."}}
    ]
  },
  "problem": {
    "title": {"ru": "...", "en": "..."},
    "points": [{"ru": "...", "en": "..."}]
  },
  "vision": {
    "title": {"ru": "...", "en": "..."},
    "body": {"ru": "...", "en": "..."},
    "bullets": [{"ru": "...", "en": "..."}]
  },
  "items": [
    {
      "slug": "item-1",
      "name": {"ru": "...", "en": "..."},
      "concept_tag": {"ru": "...", "en": "..."},
      "tagline": {"ru": "...", "en": "..."},
      "investment_usd": "$...",
      "annual_revenue_usd": "$... or null",
      "payback_years": "... лет or null",
      "key_infrastructure": [{"ru": "...", "en": "..."}],
      "revenue_mix": [{"ru": "...", "en": "..."}],
      "target_segment": {"ru": "...", "en": "..."},
      "differentiator": {"ru": "...", "en": "..."}
    }
  ],
  "financial_summary": {
    "title": {"ru": "Сводная финансовая модель", "en": "Consolidated financials"},
    "total_investment": "$...",
    "blended_payback": "... лет",
    "currency_note": {"ru": "...", "en": "..."},
    "items_breakdown": [
      {"item_slug": "item-1", "investment": "$...", "revenue": "$...", "payback": "..."}
    ]
  },
  "roadmap": {
    "title": {"ru": "Дорожная карта", "en": "Implementation roadmap"},
    "phases": [
      {
        "phase_number": 1,
        "name": {"ru": "...", "en": "..."},
        "duration": {"ru": "Q1 2026", "en": "Q1 2026"},
        "deliverables": [{"ru": "...", "en": "..."}]
      }
    ]
  },
  "team": {
    "title": {"ru": "Партнёры и команда", "en": "Partners and team"},
    "entities": [{"ru": "...", "en": "..."}]
  },
  "ask": {
    "title": {"ru": "Запрос", "en": "The ask"},
    "headline": {"ru": "...", "en": "..."},
    "supporting_points": [{"ru": "...", "en": "..."}]
  },
  "image_credits": []
}

Если в описании недостаточно данных для полного заполнения — заполняй то что можешь, остальное ставь null или "требует уточнения / TBD". Но ОБЯЗАТЕЛЬНО заполняй cover, vision, items (хотя бы 1), financial_summary, roadmap (хотя бы 2 фазы), ask.

Верни ТОЛЬКО JSON. Никаких комментариев до или после.`;

export async function POST(request: Request) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: { code: "config", message: "ANTHROPIC_API_KEY not set. Add it in Vercel environment variables." } },
      { status: 500 },
    );
  }

  let body: { text: string; projectId?: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: { code: "validation", message: "Invalid JSON body" } },
      { status: 400 },
    );
  }

  if (!body.text || body.text.trim().length < 10) {
    return NextResponse.json(
      { error: { code: "validation", message: "Provide a project description (at least 10 characters)" } },
      { status: 400 },
    );
  }

  try {
    const client = new Anthropic({ apiKey });

    const msg = await client.messages.create({
      model: "claude-sonnet-4-6-20250514",
      max_tokens: 8000,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: body.text }],
    });

    const raw = (msg.content[0] as { type: string; text: string }).text.trim();

    let json = raw;
    if (json.startsWith("```")) {
      json = json.split("```")[1];
      if (json.startsWith("json")) json = json.slice(4);
      json = json.trim();
    }

    const deck = JSON.parse(json);

    return NextResponse.json({ deck });
  } catch (err) {
    const message = err instanceof Error ? err.message : "AI generation failed";
    return NextResponse.json(
      { error: { code: "ai_error", message } },
      { status: 500 },
    );
  }
}
